name: Dockerize Production Version of React App

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: reacttestregistry.azurecr.io
          username: ${{ secrets.ACR_USERNAME}}
          password: ${{ secrets.ACR_PASSWORD}}

      - name: Build and push container image to ACR
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: reacttestregistry.azurecr.io/react-test-proj:${{ github.sha }}, reacttestregistry.azurecr.io/react-test-proj:latest
          file: ./Dockerfile
